### ISSUE TITLE
libavresample dependency

### ISSUE THREAD

**Issue by fabiencastan** [mikrosimage/avTranscoder#189]
There is a dependency to libavresample.so but it is not declared in cmake so its not copied during the make install.

$ ldd libavtranscoder.so
	linux-vdso.so.1 =>  (0x00007ffdbc99a000)
	libavformat.so.54 (0x00007feaa9fa1000)
	libavcodec.so.54 (0x00007feaa924a000)
	libavutil.so.52 (0x00007feaa9025000)
	libswscale.so.2 (0x00007feaa8dde000)
	libavresample.so.1 => /usr/lib/x86_64-linux-gnu/libavresample.so.1 (0x00007feaa8b8b000)

**Comment by cchampet** [comment]
avTranscoder can depend on ffmpeg or libav. ffmpeg uses ```swresample``` whereas libav uses ```avresample``` to process audio transform.
We declare it here: https://github.com/mikrosimage/avTranscoder/blob/develop/src/CMakeLists.txt#L6
The real problem is when cmake finds both swresample and avresample: the avtranscoder binary depend on both library.

For Tuttle, a solution could be to also declare ```avresample``` when looking for ffmpeg libraries:
https://github.com/tuttleofx/TuttleOFX/blob/develop/plugins/image/io/AudioVideo/CMakeLists.txt#L8

**Comment by fabiencastan** [comment]
We need to modify the cmake rules. Detect the fork (regarding the header) and choose the lib.
